version: "3.9"

services:

  nginx:
    image: nginx:latest
    ports:
    - 127.0.0.1:80:80
    volumes:
    - ./app:/var/www/html
    - ./configs/nginx:/etc/nginx/conf.d
    - ./logs/nginx:/var/log/nginx


  php-fpm:
    build:
      context: php-fpm
    ports:
    - 127.0.0.1:81:80
    volumes:
    - ./app:/var/www/html
    environment:
      PHP_IDE_CONFIG: "serverName=Docker"


  mariadb:
    image: mariadb:10.4
    ports:
    - 127.0.0.1:3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: rootroot
      MYSQL_DATABASE: testdb
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_pass
    volumes:
    - ./databases/mariadb:/var/lib/mysql

  phpmyadmin:
    image: arm64v8/phpmyadmin
    ports:
    - 127.0.0.1:8080:80
    environment:
      PMA_HOST: mariadb
      PMA_USER: root
      PMA_PASSWORD: rootroot
